version: "3.3"

services:
    mongodb:
        container_name: mongodb
        image: mongo:5.0
        restart: unless-stopped
        ports:
            - ${MONGO_PORT}:27017
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - ./volumes/mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
            - ~/tickets/mongodb/configdb:/data/configdb
            - ~/tickets/mongodb/db:/data/db
            - ~/tickets/mongodb/backup:/opt/backup